### ISSUE TITLE
View > Slides Home > Slides Home view does not have image style set

### ISSUE THREAD

**Issue by MiliStJohn** [energycircle/ec_slide#1]
Structure > Views > Slides Home > Home Slides(Naming convention..) > Slides Image

The "Slides Image" field of the home slides pane does not have an image style on spinup. Please change the image style to 1280x440 by default
<img width="1050" alt="screen shot 2016-08-30 at 10 34 28 am" src="https://cloud.githubusercontent.com/assets/15463763/18093458/e79013bc-6e9d-11e6-854e-a25512a6a961.png">

**Comment by flux423** [comment]
You can see in the code below, it was the Image Preset that was missing. Changing that to sc_1280x440 for now until we build out the MC for this size.

  /* Field: Content: Slide image */
  $handler->display->display_options['fields']['field_slide_image']['id'] = 'field_slide_image';
  $handler->display->display_options['fields']['field_slide_image']['table'] = 'field_data_field_slide_image';
  $handler->display->display_options['fields']['field_slide_image']['field'] = 'field_slide_image';
  $handler->display->display_options['fields']['field_slide_image']['label'] = '';
  $handler->display->display_options['fields']['field_slide_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_slide_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_slide_image']['settings'] = array(
    'image_style' => 'hero-slider',
    'image_link' => '',
  );
